// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH71s053Lh4mz4nLwEUI1nZwAq15GuFEk',
    appId: '1:212910226103:web:8aba20ff8c49c0b28aeb32',
    messagingSenderId: '212910226103',
    projectId: 'notification-options',
    authDomain: 'notification-options.firebaseapp.com',
    storageBucket: 'notification-options.appspot.com',
    measurementId: 'G-86EQ4D6NEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJm4pOqgLEmXDzDBPXPqm-Co6c5rK3Bs',
    appId: '1:212910226103:android:a6ce85059e9f65ad8aeb32',
    messagingSenderId: '212910226103',
    projectId: 'notification-options',
    storageBucket: 'notification-options.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1T5Q-OlWZhXPgqgStJthPLOGbA-_xe0c',
    appId: '1:212910226103:ios:01ae0b34ef9533cd8aeb32',
    messagingSenderId: '212910226103',
    projectId: 'notification-options',
    storageBucket: 'notification-options.appspot.com',
    iosClientId: '212910226103-80bq6lstvcocssv0ok61v7eedp6aq2lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
